# Generated by Django 4.2.25 on 2025-11-05 19:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="devicetoken",
            new_name="notificatio_platfor_0d3ecd_idx",
            old_name="notifications_platform_idx",
        ),
        migrations.RenameIndex(
            model_name="devicetoken",
            new_name="notificatio_created_3a31f4_idx",
            old_name="notifications_created_at_idx",
        ),
        migrations.AlterField(
            model_name="devicetoken",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
