# Generated by Django 4.2.25 on 2025-11-16 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_magiclink"),
    ]

    operations = [
        # Convert User.id from BigAutoField to UUIDField
        migrations.RunSQL(
            sql="""
            ALTER TABLE users_user
            ALTER COLUMN id TYPE uuid USING (gen_random_uuid());
            ALTER TABLE users_user
            ALTER COLUMN id SET DEFAULT gen_random_uuid();
            """,
            reverse_sql="""
            ALTER TABLE users_user
            ALTER COLUMN id SET DEFAULT nextval('users_user_id_seq');
            ALTER TABLE users_user
            ALTER COLUMN id TYPE bigint USING (hashtext(id::text)::bigint);
            """,
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
